name: string_validator
version: 1.0.1
description: Dart library for validating and sanitizing strings, especially
  those from user input.
homepage: https://github.com/suragch/string_validator

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.23.1
